### PR TITLE
[R] Remove pedantic warning

### PR DESCRIPTION
**Pull request by krlmlr**
about extra semicolon.

### CODE REVIEW

**Comment by krlmlr** [comment]
@jimhester: What could have caused the sudden drop in lines measured?

**Comment by jimhester** [comment]
It looks like the R results were not included in the codecov results, which is why the line measured dropped.

**Comment by krlmlr** [comment]
Thanks. Can this be fixed, do we need to do anything to fix it?

**Comment by jimhester** [comment]
The builds don't seem to be aggregating properly the last few commits. R travis is currently broken due to an unrelated issue with TexLive, so nothing we can do right now.

**Pull request closed without merging**
