### PR TITLE
[R] Set factor codes to 0-based when writing to Feather file

### LINKED ISSUE #108: Factor/categorical levels getting shuffled around?
Using R magic in a Jupyter notebook on Ubuntu (Python 3.5.1, pandas 0.17.1, R 3.2.4). The species values seem to be getting shuffled around. 

```python
%%R 
> head(iris)
```

      Sepal.Length Sepal.Width Petal.Length Petal.Width Species
    1          5.1         3.5          1.4         0.2  setosa
    2          4.9         3.0          1.4         0.2  setosa
    3          4.7         3.2          1.3         0.2  setosa
    4          4.6         3.1          1.5         0.2  setosa
    5          5.0         3.6          1.4         0.2  setosa
    6          5.4         3.9          1.7         0.4  setosa

```python
%%R
str(iris)
# Species variable stored as factor, not string
```

    'data.frame':	150 obs. of  5 variables:
     $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
     $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
     $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
     $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
     $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...

```python
%%R
## Write R dataframe to disk
> write_feather(iris, 'iris.feather')
```

```python
## Read into a pandas dataframe
> iris_pd = feather.read_dataframe('iris.feather')
```

```python
> print(iris_pd.head())
```
       Petal.Length  Petal.Width  Sepal.Length  Sepal.Width     Species
    0           1.4          0.2           5.1          3.5  versicolor
    1           1.4          0.2           4.9          3.0  versicolor
    2           1.3          0.2           4.7          3.2  versicolor
    3           1.5          0.2           4.6          3.1  versicolor
    4           1.4          0.2           5.0          3.6  versicolor

```python

> pd_iris.dtypes
```
    Petal.Length     float64
    Petal.Width      float64
    Sepal.Length     float64
    Sepal.Width      float64
    Species         category
    dtype: object

### PR DESCRIPTION
**Pull request by wesm**
Closes #108 

I had to update some Feather files in `R/inst/feather` because this changed the on-disk files. I still need to add a version number to the file metadata.

### CODE REVIEW

**Comment by wesm** [comment]
moving this comment out of the PR description


cc @hadley @krlmlr I am getting the following test failures that are outside my domain of knowledge:

```R
> testthat::test_package("feather")
class : .......1.2.............
read : .34
roundtrip-vector : ....................

1. Failure (at test-class.R#17): basic access ----------------------------------
iris.f[, 1:5] is not identical to iris.tbl[, 1:5]. Differences: 
Objects equal but not identical

2. Failure (at test-class.R#19): basic access ----------------------------------
iris.f[1:5] is not identical to iris.tbl[1:5]. Differences: 
Objects equal but not identical

3. Failure (at test-read.R#6): multiplication works ----------------------------
read_feather(iris_example, columns = 1:3) is not identical to as_data_frame(iris)[1:3]. Differences: 
Objects equal but not identical

4. Failure (at test-read.R#8): multiplication works ----------------------------
read_feather(iris_example, columns = "Species") is not identical to as_data_frame(iris)["Species"]. Differences: 
Objects equal but not identical
Error: Test failures
```

**Comment by wesm** [comment]
I added a version number. Let me know if this looks good, as we should get this shipped soon to avoid accidental bad data getting read by Python users =|

**Comment by krlmlr** [comment]
I can't replicate the test failures in dad02f13d7.

**Comment by wesm** [comment]
Bumping the commit hash to get a new build, then merging on green. We should advise Feather users to update. I will tag a v0.2.0 release if that sounds good to all

**Comment by wesm** [comment]
@hadley @krlmlr it occurs to me that NA values in factors are probably handled incorrectly here. I opened #117 to track -- could one of you write a test case for this to verify one way or the other (since the codes were being written unmodified before, it is likely incorrect now)? Might have to test this with an integration test (Python generating null data in an int8 or int16-encoded factor).

**Comment by wesm** [comment]
I'll try to write some tests to check the cases I'm talking about (these are bugs that I may have introduced in https://github.com/wesm/feather/commit/06e69b0af92505e94ac785daf6c7f7d09236580c).

**Pull request closed without merging**
