### PR TITLE
[R] Release prep

### PR DESCRIPTION
**Pull request by hadley**
Probably worth letting this percolate for a bit so I can add other small release related stuff.

Have we decided on a version number? 0.1.0?

### CODE REVIEW

**Comment by wesm** [comment]
Based on https://github.com/wesm/feather/releases I would say this is 0.3.0

**Comment by wesm** [comment]
I'm taking care of #208 now and will add some Python release notes

**Comment by hadley** [comment]
I'm ready for release. Just give the word!

**Comment by wesm** [comment]
Sweet, I'm ready too. Want me to merge this and #220 and tag the release?

**Comment by hadley** [comment]
Let me submit to CRAN first, just to be sure there are no hiccups there.

**Pull request closed without merging**
