### PR TITLE
[C++] Add WritePadded methods and pad all memory buffers to 8 byte boundaries

### LINKED ISSUE #213: Align buffer writes on 8 byte boundaries
This will help other implementations (e.g. JS) that depend on aligned memory access

### PR DESCRIPTION
**Pull request by wesm**
This patch ensures that all the memory buffers in the file fall on aligned / padded 64-bit word boundaries, to improve cross-language compatibility per the discussion in #17. 

This has the downside of making existing Feather files unreadable, but we never told anyone they were going to be portable between versions while the project is new anyway. With some effort I could add backwards compatibility -- @hadley what do you think? 

Closes #213

### CODE REVIEW

**Comment by wesm** [comment]
I added an error message if the user tries to read an older file (here, created with the last released version):

```python
In [1]: import feather
fe
In [2]: feather.read_dataframe('test.f2')
---------------------------------------------------------------------------
FeatherError                              Traceback (most recent call last)
<ipython-input-2-328f40c3c8fb> in <module>()
----> 1 feather.read_dataframe('test.f2')

/home/wesm/code/feather/python/feather/api.py in read_dataframe(path, columns)
     56     df : pandas.DataFrame
     57     """
---> 58     reader = ext.FeatherReader(path)
     59 
     60     if columns is not None:

/home/wesm/code/feather/python/feather/ext.pyx in feather.ext.FeatherReader.__cinit__ (feather/ext.cpp:3704)()
    212             string c_name = encode_file_path(name)
    213 
--> 214         check_status(TableReader.OpenFile(c_name, &self.reader))
    215 
    216     property num_rows:

/home/wesm/code/feather/python/feather/ext.pyx in feather.ext.check_status (feather/ext.cpp:1666)()
     53 
     54     cdef string c_message = status.ToString()
---> 55     raise FeatherError(frombytes(c_message))
     56 
     57 set_numpy_nan(np.nan)

FeatherError: Invalid: Feather file is version 1 but only able to read files with version 2
```

This error message will be the same in R

**Comment by wesm** [comment]
I updated the `inst/feather/*.feather` files to get the R test suite passing

**Comment by hadley** [comment]
Hmmmm, it's a bit of a bummer to break backwards compat. How much work would it be to read both versions?

Maybe we should be writing a nominal version number to help ameliorate this problem?

**Comment by wesm** [comment]
There is a version number in the metadata now. I can make this version backwards compatible without too much work but I will have it print a warning that 0.2.0 files will only be readable in 0.3.0 but not beyond.

**Comment by hadley** [comment]
I think that's a reasonable compromise

**Comment by wesm** [comment]
```python
In [2]: feather.read_dataframe('test.feather')
This Feather file is old and will not be readable after the 0.3.0 release
Out[2]: 
          0         1        10        11         2         3         4  \
0 -0.915188 -0.915188 -0.915188 -0.915188 -0.915188 -0.915188 -0.915188   
1  1.006112  1.006112  1.006112  1.006112  1.006112  1.006112  1.006112   
2  1.105041  1.105041  1.105041  1.105041  1.105041  1.105041  1.105041   
3 -1.130068 -1.130068 -1.130068 -1.130068 -1.130068 -1.130068 -1.130068   
4  0.135700  0.135700  0.135700  0.135700  0.135700  0.135700  0.135700   
5  1.007858  1.007858  1.007858  1.007858  1.007858  1.007858  1.007858   
6  1.630852  1.630852  1.630852  1.630852  1.630852  1.630852  1.630852   
7 -0.717823 -0.717823 -0.717823 -0.717823 -0.717823 -0.717823 -0.717823   
8  0.918637  0.918637  0.918637  0.918637  0.918637  0.918637  0.918637   
9 -0.627237 -0.627237 -0.627237 -0.627237 -0.627237 -0.627237 -0.627237   

          5         6         7         8         9  
0 -0.915188 -0.915188 -0.915188 -0.915188 -0.915188  
1  1.006112  1.006112  1.006112  1.006112  1.006112  
2  1.105041  1.105041  1.105041  1.105041  1.105041  
3 -1.130068 -1.130068 -1.130068 -1.130068 -1.130068  
4  0.135700  0.135700  0.135700  0.135700  0.135700  
5  1.007858  1.007858  1.007858  1.007858  1.007858  
6  1.630852  1.630852  1.630852  1.630852  1.630852  
7 -0.717823 -0.717823 -0.717823 -0.717823 -0.717823  
8  0.918637  0.918637  0.918637  0.918637  0.918637  
9 -0.627237 -0.627237 -0.627237 -0.627237 -0.627237  
```

**Comment by wesm** [comment]
Merging this on a green build. Then I'm ready to release when you are!

**Pull request closed without merging**
