### PR TITLE
[R] release 0.3.4 (fixes #374)

### LINKED ISSUE #374: Incompatibility with tibble>=2.0.0
After upgrading to tibble 2.0.1 for another library read_feather is giving this error:

```Error: evaluation nested too deeply: infinite recursion / options(expressions=)?```

Has anyone seen this before? do we just need to recompile feather or is it not compatible with this new version?

### PR DESCRIPTION
**Pull request by jameslamb**
@hadley for your consideration...I prepped a release for the R package that makes the `tibble` version floor clearer (per our discussion on #374 )

If you think #375 is not ready to go yet and needs some review, I think it would be valuable to do the release in this PR ASAP.

Thanks!

### CODE REVIEW

**Comment by hadley** [comment]
0.3.3 is on CRAN, so this doesn't seem right to me.

**Comment by jameslamb** [comment]
oh [you're right](https://cran.r-project.org/web/packages/feather/index.html). Should've checked CRAN instead of making assumptions based on #375 !

**Comment by jameslamb** [comment]
Bumped version to `0.3.4` in `0671f41`.

**Comment by hadley** [comment]
I think this is just easier for me to do — generally you shouldn't attempt to do a release in PR like this.

**Pull request closed without merging**
