### PR TITLE
[R] Fixes for R package on windows

### PR DESCRIPTION
**Pull request by hadley**
Unfortunately overlaps with #140 since it seems like we were working in parallel.

### CODE REVIEW

**Comment by jeroenooms** [comment]
That's fine. Note that if you use `throw std::runtime_error()` instead of `Rcpp:;stop()`, the compiler will understand the function exits and you do not have to add another `return` statement.

Also note the fix in `status.cc` in my PR.

**Comment by wesm** [comment]
can this be merged?

**Comment by hadley** [comment]
I'll integrate @jeroenooms's changes with mine and I'll let you know when it's ready. Probably early next week.

**Comment by hadley** [comment]
@wesm this is good to merge - once you've merged I'll submit to CRAN.

**Comment by wesm** [comment]
awesome, thanks

**Pull request closed without merging**
