### PR TITLE
[R] prepare for R CRAN release

### PR DESCRIPTION
**Pull request by kevinushey**
cc: @hadley @wesm; I don't think there's anything else needed beyond bumping the version number here?

### CODE REVIEW

**Comment by hadley** [comment]
LGTM

**Comment by wesm** [comment]
+1

**Comment by kevinushey** [comment]
Thanks! feather 0.3.1 is now on CRAN and successfully builds with gcc-4.4 :)

**Comment by wesm** [comment]
awesome, thanks!

**Pull request closed without merging**
