### PR TITLE
[R]: Install package dependencies as binaries

### PR DESCRIPTION
**Pull request by jimhester**

### CODE REVIEW

**Comment by jimhester** [comment]
This should speed up the R builds a significant amount.

**Comment by wesm** [comment]
Thanks -- why does this build depend on so many packages?

**Comment by jimhester** [comment]
dplyr and testthat dependencies mostly, packages in Suggests get installed on travis because they are likely used in building vignettes and tests.

**Comment by hadley** [comment]
The dependencies are heavier for developers because we need all the downstream suggested packages - they're considerably lighter for users.  (And generally, the R community doesn't care that much about heavy deps)

**Pull request closed without merging**
