### PR TITLE
[R]: Read-only data.frame-like interface to feather storage

### PR DESCRIPTION
**Pull request by krlmlr**
- data.frame-like interface to feather storage (read-only)

### CODE REVIEW

**Comment by wesm** [comment]
Can you rebase (let me know when this is reviewed / ready for merge)? Also, perhaps not in this patch, but it would be great to add an R build to the Travis CI matrix:

https://github.com/wesm/feather/blob/master/.travis.yml

I need to do the same for Python

**Comment by krlmlr** [comment]
Rebased. The tests pass locally, but I'd like @hadley to comment on the design.

Travis would be much easier if the R package was hosted separately. Library could be pulled in via "Git subtree".

**Comment by hadley** [comment]
I think the overall approach is good - but this is overselling it. It behaves like a data frame in some cases, but many methods will fail because it's not actually a data frame. While you could add feather methods to many generics, there are some things that you just can't fix (e.g. `lm()`). I'd rather make it behave less like a data frame and more like its own thing, i.e. an immutable file backed data frame.

In practice, I think this means tweaking the print method to make it clear that this is not a regular data frame, and maybe making the translation to an explicit data frame more explicit (i.e. with a `collect()` method)

**Comment by krlmlr** [comment]
Thanks. Now print includes the correct source:

```
> feather(feather_example("mtcars.feather"))
Source: feather store [32 x 11]

     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1   21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
2   21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
3   22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
4   21.4     6 258.0   110  3.08 3.215 19.44     1     0     3     1
5   18.7     8 360.0   175  3.15 3.440 17.02     0     0     3     2
6   18.1     6 225.0   105  2.76 3.460 20.22     1     0     3     1
7   14.3     8 360.0   245  3.21 3.570 15.84     0     0     3     4
8   24.4     4 146.7    62  3.69 3.190 20.00     1     0     4     2
9   22.8     4 140.8    95  3.92 3.150 22.90     1     0     4     2
10  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
```

I have found that `lm()` just works, but of course there may be cases which don't. You can always get to a data frame with as.data.frame() and as_data_frame(). (This even might be a more intuitive verb than collect(), I tend to confuse the coxxx() verbs in dplyr). For reference:

```
> feather(feather_example("mtcars.feather")) %>% lm(f = wt~hp)

Call:
lm(formula = wt ~ hp, data = .)

Coefficients:
(Intercept)           hp  
   1.838247     0.009401  
```

I'll file the first three commits as a separate PR. Will work more on the fourth commit (the S3 class).

**Comment by hadley** [comment]
Ok, I think that's reasonable for a first pass. I think we do also need to add support for only reading specified rows and cols in `read_feather()`.

**Comment by wesm** [comment]
Merged the other patches.

**Comment by krlmlr** [comment]
Rebased. Will base further work on this commit.

- I think the easiest way to achieve column subsetting in read_feather() is to use the new feather class. Some Rcpp functions will become obsolete, too.
- I see a way to fix `names()`.

**Comment by hadley** [comment]
LGTM

**Comment by wesm** [comment]
Shoot, I merged things in the wrong order. You're giving me nice clean patches, too =) Won't happen again.

**Pull request closed without merging**
