### PR TITLE
[Dev] Adding code coverage for C++ and python code

### PR DESCRIPTION
**Pull request by jimhester**
The CPP code coverage requires you to compile without optimizations to ensure accurate reporting. If this is an issue we could have a separate build for coverage.

Using the bash uploader in this fashion is the recommended approach from codecov (https://github.com/codecov/example-c). If you are not comfortable doing that we could add the script from https://github.com/codecov/codecov-bash to `$FEATHER_CPP/ci` directly and simply source that.

### CODE REVIEW

**Comment by jimhester** [comment]
The previous CMakeLists.txt file was overwriting the value of `CMAKE_CXX_FLAGS` in all cases rather than appending the various flags for each build type. This caused values passed as `-DCMAKE_CXX_FLAGS="..."` (including the previous `-Werror`) to be ignored. https://github.com/wesm/feather/pull/101/commits/aebfaa48bdefac0fd3f33567e3ec6f3cc04e6953 addresses that issue.

**Comment by jimhester** [comment]
It looks like while the CPP coverage worked (https://travis-ci.org/wesm/feather/jobs/120912585#L645-L1055) you will need to fixup the CPP file paths in order for the reporting to work properly (https://codecov.io/github/wesm/feather/features/fixpaths). That should only need to be done once IIRC.

**Comment by jimhester** [comment]
Also if you want to set up the C++ coverage as mentioned in https://github.com/wesm/feather/issues/20 let me know and I can adjust the Cmake file accordingly. I did not see that issue when I started this PR and this is currently a less invasive change.

**Comment by wesm** [comment]
Thank you for this, and for fixing the CXX flags issue! I will tweak the file paths in codecov to get nice reporting

**Pull request closed without merging**
