### PR TITLE
added 'description' param to 'write_feather()'

### PR DESCRIPTION
**Pull request by hrbrmstr**
based on this q — https://stackoverflow.com/questions/47896468/how-to-add-optional-dataset-description-to-feather-file — I added a `description` parameter to the R pkg `write_feather()`.

### CODE REVIEW

**Comment by vnijs** [comment]
In R the dataset description could be added as an attribute. Would something like the following be reasonable for a data.frame that already has a description attached?

    write_feather <- function(x, path, description = attr(x, "description"))

It would also be convenient if `read_feather` added the description, if available, as an attribute to the data.frame

**Comment by hrbrmstr** [comment]
aye. I can make those changes. #ty for the feedback/suggestion!

**Comment by wesm** [comment]
Can someone review this PR?

**Comment by vnijs** [comment]
See also related feature request for similar functionality on the Python side: https://github.com/wesm/feather/issues/328

**Comment by wesm** [comment]
Sorry for the eternal delay on this. We've created the Feather V2 format in http://github.com/apache/arrow -- if there is desire to add this functionality to V2 (which uses the Arrow IPC format) can you please open a JIRA issue with Apache Arrow?

**Pull request closed without merging**
