### PR TITLE
[C++]: add mman.h on windows. close #71

### LINKED ISSUE #71: Windows build fails due to missing sys/mann.h
I am trying to build feather on Windows7 64bit using R-patched (3.2.4) and Rtools 3.3.0 V1959 (as discussed in https://github.com/wesm/feather/issues/58). I sort-of followed @wesm's advice by cloning the repository and manually taking the actions in the [R/configure](https://github.com/wesm/feather/blob/master/R/configure). The build proceeds until [io.cc](https://github.com/wesm/feather/blob/master/cpp/src/feather/io.cc) whereupon it fails as Windows installations of gcc do not have sys/mann.h

The older answers (like in SO) which directed one to https://code.google.com/archive/p/mman-win32/ are not useful as that is a dead link now. Can anything be done to get around this?

Thank you.

### PR DESCRIPTION
**Pull request by thirdwing**
This should work well just like in RcppAnnoy.

### CODE REVIEW

**Comment by aadler** [comment]
I should be able to, yes.

**Comment by aadler** [comment]
It compiles properly, but trying write_feather gives me the following error:

```
> A <- data.frame(L = letters[1:10], N = rnorm(10, 0, 1))
> A
   L          N
1  a -1.2891161
2  b  0.7430167
3  c  0.2887883
4  d  0.8691783
5  e  0.1244797
6  f -0.2427546
7  g  2.0343529
8  h -0.4095575
9  i -1.5355897
10 j -0.5314808
> write_feather(A, "E:/Users/Parents")
 Hide Traceback
 
 Rerun with Debug
 Error: IO error: error closing file 
3 stop(structure(list(message = "IO error: error closing file", 
    call = NULL, cppstack = NULL), .Names = c("message", "call", 
"cppstack"), class = c("Rcpp::exception", "C++Error", "error", 
"condition"))) 
2 writeFeather(x, path) at feather.R#29
1 write_feather(A, "E:/Users/Parents") 
```
and running with debug stops at this line:
```
writeFeather <- function(df, path) {
    invisible(.Call('feather_writeFeather', PACKAGE = 'feather', df, path))
```

**Comment by thirdwing** [comment]
@aadler Maybe related to #68

**Comment by aadler** [comment]
@thirdwing It shouldn't; I had no empty characters in the data frame. Also, it wasn't a segfault but `IO error: error closing file `.

**Comment by aadler** [comment]
@thirdwing,  I've made a stupid error. When I put in the path, I didn't select a file name, just a path. It works fine! @hadley and @wesm , the pull request tests out well and should be committed, IMO.

**Comment by wesm** [comment]
merging, thank you everyone

**Pull request closed without merging**
